# Generated by Django 3.1.5 on 2021-01-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210131_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
