# Generated by Django 3.1.5 on 2021-02-02 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210202_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postblogmodel',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='postworkmodel',
            name='published_at',
        ),
    ]
