# Generated by Django 3.1.5 on 2021-02-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_categorymodel_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='name',
            new_name='category',
        ),
    ]
