# Generated by Django 3.1.6 on 2021-02-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210203_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblogmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogimages/'),
        ),
        migrations.AddField(
            model_name='postworkmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogimages/'),
        ),
    ]
